
SELECT TRAIN_ID FROM TRAIN_INFO
WHERE TOTAL_SEAT>30

SELECT SUM (PAID_AMOUNT) FROM TRAVEL_INFO WHERE DATE='2016-11-22';

SELECT TRAIN_ID, TOTAL_SEAT-(SELECT COUNT (TRAVEL_NO) FROM TRAVEL_INFO WHERE TRAVEL_INFO.TRAIN_ID=TRAIN_INFO.TRAIN_ID AND DATE="2016-11-22" AND TIME="5:06") AS AVAILABLE_SEAT FROM TRAIN_INFO;


CREATE VIEW TRAVEL_INFO_2016_11_22 AS 
SELECT TRAVEL_NO, PASSENGER_ID, TRAIN_ID, STATION_A, STATION_B, PAID_AMOUNT 
FROM TRAVEL_INFO WHERE DATE="2016-11-22";

SELECT * FROM TRAVEL_INFO_2016_11_22;

DELETE FROM TRAVEL_INFO WHERE DATE="2016-11-22";
